name: NodeJS Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: nodejsscan
      id: nodejsscan
      uses: ajinabraham/njsscan-action@v5
      with:
        args: '.'
