name: PR lint

on:
  pull_request:
    types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
  pr-lint:
    runs-on: ubuntu-latest
    steps:
    - uses: hayuna/pr-lint-action@v1.2
      with:
        title-regex: '^\FRDQ-\d+( - )?.*'
        title-regex-flags: 'g' # optional
        error-message: 'Add Vivify ID to your title'
