name: Publish storybook
on: [push, pull_request]
jobs:
  custom_command:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Install
        run: yarn
      - name: Percy Test
        uses: percy/storybook-action@v0.1.1
        with:
          custom-command: 'yarn build-storybook'
        env:
          PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
